Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Please explain why we need this dependency. Are they not pulled in from policy-common?

Hi Liam, Without adding kafka.clients dependency, ClassNotFoundException's are observed for all org.apache.kafka.clients classes while changing configuration to use Kafka instead of Dmaap.

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/clients/consumer/KafkaConsumer
	at org.onap.policy.common.endpoints.event.comm.bus.internal.BusConsumer$KafkaConsumerWrapper.<init>(BusConsumer.java:287)
	...
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.consumer.KafkaConsumer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

Patch-set: 1